version: 2
updates:
  - package-ecosystem: "github-actions" # Necessary to update action hashes	
    directory: "/"
    schedule:
      interval: "weekly"
    # Allow up to 2 opened pull requests for github-actions versions
    open-pull-requests-limit: 2

